test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: minibars_staging
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: minibars_production
  username: root
  password: ''
